# SSM Parameter for API auth - value generated by Terraform (random_password) and passed here
resource "aws_ssm_parameter" "api_token" {
  name        = "/${var.project_name}/${var.environment}/api/token"
  description = "API authentication value (generated by Terraform)"
  type        = "SecureString"
  value       = var.api_auth_value

  tags = {
    Name        = "${var.project_name}-api-token"
    Environment = var.environment
  }
}
