#!/usr/bin/env bash
# Creates S3 bucket and DynamoDB table for Terraform state backend.
# Run once from repo root: ./scripts/bootstrap-backend.sh
# Then: cd terraform && terraform init -reconfigure -backend-config=backend.s3.tfvars

set -e

AWS_REGION="${AWS_REGION:-us-west-1}"
BUCKET_PREFIX="${BUCKET_PREFIX:-devops-exam-terraform-state}"
LOCK_TABLE="${LOCK_TABLE:-devops-exam-terraform-lock}"
KEY_PREFIX="${KEY_PREFIX:-devops-exam/terraform.tfstate}"

echo "Bootstrap Terraform S3 backend (region=$AWS_REGION)"

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null) || {
  echo "Error: AWS CLI not configured or no credentials. Run 'aws configure'." >&2
  exit 1
}

BUCKET_NAME="${BUCKET_PREFIX}-${ACCOUNT_ID}"
BACKEND_FILE="terraform/backend.s3.tfvars"

echo "Using bucket: $BUCKET_NAME"
echo "Using DynamoDB table: $LOCK_TABLE"

# Create S3 bucket if it doesn't exist
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
  echo "S3 bucket $BUCKET_NAME already exists."
else
  echo "Creating S3 bucket $BUCKET_NAME ..."
  aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION" \
    $([ "$AWS_REGION" != "us-east-1" ] && echo "--create-bucket-configuration LocationConstraint=$AWS_REGION")
  echo "Enabling versioning ..."
  aws s3api put-bucket-versioning --bucket "$BUCKET_NAME" \
    --versioning-configuration Status=Enabled
  echo "Enabling encryption (default AES256) ..."
  aws s3api put-bucket-encryption --bucket "$BUCKET_NAME" \
    --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
  echo "S3 bucket $BUCKET_NAME created."
fi

# Create DynamoDB table if it doesn't exist
if aws dynamodb describe-table --table-name "$LOCK_TABLE" --region "$AWS_REGION" 2>/dev/null | grep -q TableName; then
  echo "DynamoDB table $LOCK_TABLE already exists."
else
  echo "Creating DynamoDB table $LOCK_TABLE ..."
  aws dynamodb create-table --table-name "$LOCK_TABLE" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "$AWS_REGION"
  echo "Waiting for table to be active ..."
  aws dynamodb wait table-exists --table-name "$LOCK_TABLE" --region "$AWS_REGION"
  echo "DynamoDB table $LOCK_TABLE created."
fi

# Write backend config file
mkdir -p terraform
cat > "$BACKEND_FILE" << EOF
# Generated by scripts/bootstrap-backend.sh - do not edit by hand
bucket         = "$BUCKET_NAME"
key            = "$KEY_PREFIX"
region         = "$AWS_REGION"
encrypt        = true
dynamodb_table = "$LOCK_TABLE"
EOF

echo ""
echo "Wrote $BACKEND_FILE"
echo ""
echo "Next steps:"
echo "  cd terraform"
echo "  terraform init -reconfigure -backend-config=backend.s3.tfvars"
echo "  terraform plan -var-file=environments/prod/terraform.tfvars"
echo "  terraform apply -var-file=environments/prod/terraform.tfvars"
echo ""
